### ISSUE TITLE
Torn boom cover / sail bag

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#191] opened 2017-08-21 19:31 UTC
The canvas boom cover has been installed too far forward on the boom and has become fouled with the reefing lines. Crew,  when attempting to adjust the position of the sail bag have inadvertently torn the canvas.

The potential for this problem was reported in issue #171 

[Here](https://goo.gl/photos/8bKesVoH8kNhkmSp6) are some photos.

@delcosta may take this up with Ensign as a warranty issues. @DaveHolt and @peterottesen will also be interested.

**Comment by smr547** [comment] 2017-08-21 19:38
Hi Dee -- @DeeTaylor87 -- while you are at the boat today, could you please get a photo of the aft end of the boom (from the side). It shows how the boom cover/sail bag is positioned too far forward on the boom. It could come back about 75mm towards the black line on the boom and this may prevent further fouling.
Many thanks, Steven

**Comment by DeeTaylor87** [comment] 2017-08-21 22:01
Unfortunately I am not at the boat today! Was there yesterday.....  I'll be there next on Friday with Jack to collect it from BME so will get a picture then.

**Comment by smr547** [comment] 2017-08-21 22:24
Thanks Dee -- my mistake. I hope it all went well. Friday photo would be good -- @delcosta wants to talk to Ensign about it. :D

**Comment by delcosta** [comment] 2017-08-21 22:49
WE need to advise Ensign.
@jphayden I will call you today

**Comment by smr547** [comment] 2017-08-21 23:47
Thanks Sam, 
and welcome aboard as a full member of the Github Maintenance Management System.
cheers
Steven

**Comment by smr547** [comment] 2017-08-22 00:37
@JCRowling might be interested in this issue

**Comment by smr547** [comment] 2017-08-22 00:43
@GarthBrice will be interested too -- he was there and was able to assess the problem first hand with @peterottesen and @smr547

**Comment by jphayden** [comment] 2017-08-22 00:59
We will have to document this very carefully and be very precise in how we describe the problem and the cause of the problem to enable warranty kind

**Comment by GarthBrice** [comment] 2017-08-22 05:33
The problem as I see it is that when the bag is pulled back to the black outhaul line on the boom so that it does not foul the reefing lines at the tack of the mainsail, the cover is not big enough to wrap around the mainsail and the mast

**Comment by smr547** [comment] 2017-08-22 05:44
Thanks Garth. 
So some alterations to the bag may be necessary -- in addition to the repair!
This work should be done when the main comes off to install 3rd reef -- see issue #47 
@DaveHolt needs to have input on this too

**Comment by DeeTaylor87** [comment] 2017-08-22 05:53
It seems to me that the boom bag never really fit. The first time I saw it
was in the first week following handover and it was impossible to do up the
buckles then. I don't remember ever seeing the top buckle done up because
it just would not meet around the mast. I can't shake the feeling that the
bag we were given was the wrong size.

**Comment by DeeTaylor87** [comment] 2017-08-29 11:57
Who should I assign to this job? @smr547 @GarthBrice @peterottesen @jphayden ?  Someone needs to take it on as their project before it moves to BB I think.

**Comment by delcosta** [comment] 2017-08-29 12:20
Perhaps whoever is looking after the 3rd Ref?
@peterottesen

**Comment by smr547** [comment] 2017-08-30 05:24
Dee, you mentioned that the sail bag may not have been designed to go around the mast? If that is true then we may have pulled the bag forward inadvertently. In which case it is our problem to fix. Then @peterottesen and sailmaker.

Having said that, it's difficult to see how the sailbag would work WITHOUT going around the mast. In which case, the bag is probably too small -- in that case it would be @jphayden to negotiate a warranty claim (and repair) with Ensign.

I think we leave it to @jphayden to guide us on this. I think Jack is due to go to the boat this week??

**Comment by jphayden** [comment] 2017-08-30 05:43
I will try and get Kate or Andy aboard on the weekend to look at the problem

**Comment by DeeTaylor87** [comment] 2017-08-31 01:48
I have more pictures. Aft and tear. Will upload later if required.

**Comment by DeeTaylor87** [comment] 2017-08-31 12:26
![aft end boom bag](https://user-images.githubusercontent.com/30706096/29922994-2fd2ad2e-8e9b-11e7-8177-5988ad64b169.jpg)
![torn boom bag](https://user-images.githubusercontent.com/30706096/29923011-44e9ba7c-8e9b-11e7-9650-a7c2e9bb5d4d.jpg)

**Comment by jphayden** [comment] 2017-09-04 20:48
Dee ,
Andy's phone no is 0438 696 157  - just in case

**Comment by DeeTaylor87** [comment] 2017-09-04 23:30
I rang Andy this morning to confirm and check timing after being caught in traffic on the way in to my 8:00am meeting.  Andy had insisted on the phone to Jack the previous day that 8:00am was the only time he had available for a meeting. When I called, I was about 15minutes away at 7:40 so was very prepared to make it in time for the meeting.

Andy however insisted that the meeting had been arranged for 10:00am.  He was a little cross, saying that he had arranged 10:00am all along.  I happily agreed to 10:00am and said I would grab a coffee and meet him at the boat at 10:00am.

A short while later, Andy rang back to say that Jack had called him yesterday and postponed the meeting till later in the week so the meeting was off. I said this was news to me and that I hadn't heard anything about the meeting being postponed. Andy was adamant that this was the case, and that if CORC couldn't get their act together, then there was little he could do about it.  I was a little taken aback by this turn of events and insisted that I thought it would be good to have a meeting so that he could see the condition of the sail bag regardless of the position of the reefs since the sailbag did not seem to be made of sufficient strength for the purpose it was designed for even without the problem of the reefs. Andy insisted that all Bavaria sailbags are made of that material and the only problem is that we don't understand how to fit it properly. He insisted that he did not want to speak to anyone other than Jack. He said he would call Jack this morning to resolve the timing of the meeting going forward. I assured him that Jack had been very supportive of Bavaria and the efforts they had made to supply us with quality materials.  I was very surprised by Andy's tone and manner this morning.  @jphayden   Have you heard from Andy? What is your understanding of the timing of the meeting?

**Comment by jphayden** [comment] 2017-09-04 23:37
I recall the discussion about the 8 o'clock meeting I don't recall the 10 o'clock meeting  but Andy was nice as pie yesterday when we spoke I think he gets upset when he has to deal with somebody he doesn't know.
 I have not heard from him yet

**Comment by DeeTaylor87** [comment] 2017-09-05 03:25
More pictures taken today of the rolled up sail bag, tied aft to get it away from the reefing lines and mast.
![sail bag 1](https://user-images.githubusercontent.com/30706096/30043868-743d1062-923d-11e7-8471-c38b98632aec.jpg)
![sail bag2](https://user-images.githubusercontent.com/30706096/30043869-75f6c952-923d-11e7-84a2-3e833cb220c1.jpg)

**Comment by DeeTaylor87** [comment] 2017-09-06 04:24
Simon has booked a repair on the Sail Cover in Bateman's Bay.  It will need to be taken off and transported for repair I think....  @srdunlop @smr547 @paulmc9999

**Comment by jphayden** [comment] 2017-09-07 04:37
Email below from Andy Howden who visited the boat today .  Email forwarded with pictures :

Hi Jack,
 
Please see photos of the bag. The bag is not designed to go around the mast and the tabs should Velcro thru the sliders as shown. When the sail is deployed and the bag open there are two bungies sewn into the inside of bag that wrap around the front of each side and loop over a hook also sewn into the boom bag on the outside of the bag just rear of the red sail elvstrom emblem. You will see shots of the sail secured back , how the bungy attaches to hook , of the hook itself and of the bag secured with sail stowed.
Obviously someone may have been confused as by forcing the bag it has ripped on the port side fore of bag. Also some extra strain has been put on other stitching points you may want to have that repaired once she gets south to stop any fraying.
 
 
 
 
Andy Howden
Director - Ensign Sydney
0438 696 157

**Comment by DeeTaylor87** [comment] 2017-09-12 10:41
@bullswool has offered to take off the bag so that it can be delivered to the repair service organised by @srdunlop while Bill has the boat in Bateman's Bay.  Please keep us informed of progress so that we can close this issue when it is resolved. Thanks Simon and Bill

**Comment by DaveHolt** [comment] 2017-09-24 01:54
Bill says: Removed boom bag for repairs at “3D Sails” B/Bay, picked up on completion, and refitted to yacht. A lazyjack line had been sewn under an attachment slider, so the swage had to be cut off and the line rerouted & retied to the attach tab.

**Closed by DaveHolt** 2017-09-24 01:54 UTC
Labels: Canvas, priority 1: High
