### ISSUE TITLE
Outboard Motor - Service

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#702] opened 2023-08-17 10:39 UTC
The Dinghy motor is stalling at low speed. A service may be required.  
Spark plug cleaned but did not fix the stalling issue. 

Task for Noumea?

**Comment by smr547** [comment] 2023-09-25 00:37
closing this issue -- duplicate of #385

**Closed by smr547** 2023-09-25 00:37 UTC
