### ISSUE TITLE
Water leak from deck shower

### ISSUE THREAD

**Issue by PSARN** [CanberraOceanRacingClub/namadgi3#454] opened 2021-11-13 22:29 UTC
There is a leak from the hot water connector for the deck showe
[IMG_0596.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/7567456/IMG_0596.pdf)
r.

**Comment by smr547** [comment] 2021-12-02 02:54
Leak was coming from the plastic hose to metal joiner at the cold water inlet of the deck shower mixer. The half inch screw fitting had worked its way loose. Nipped up with shifter and multigrips. No more leak. 

It's terrible working in that space. One has to use the engine breather tube as a back rest. Consequently the tube is becoming more and more compressed. 

Additionally the feed hoses for the mixer are unsupported and just hang in the air. Stresses on the hoses caused by the movement of the shower head hose itself are contributing to the problem. A mechanical support independent of the shower hose would be a great idea but almost impossible to install. 

Lets avoid this problem in the next boat! :D

Closing this issue.

**Closed by smr547** 2021-12-02 02:54 UTC
Labels: Working bee
