### ISSUE TITLE
Galvanic Isolation transformer to shore power circuit

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#44] opened 2017-08-04 06:31 UTC
(urgency depends on where we keep Namadgi…if on a mooring is lower priority
timing: July
estimate: $1,900

**Comment by DeeTaylor87** [comment] 2017-08-22 07:19
@smr547 @jphayden Is this the work that is being done by BME now?

**Comment by smr547** [comment] 2017-08-22 07:23
Yes

**Comment by DeeTaylor87** [comment] 2017-08-22 11:18
This is a duplicate of issue 180

**Comment by DeeTaylor87** [comment] 2017-08-27 08:10
This has been installed in the compartment between the two aft cabins.  When you open the compartment, then open the storage bay under the compartment and you will see the transformer.

**Comment by DeeTaylor87** [comment] 2017-08-28 06:44
Communication with Daniel of BME 28th August
Hi Daniel, Jack Hayden CORC here. The matters we wanted to address are: Light in the engine bay, provision of fuse kit, check the battery monitor, check the electrical cable on the forward keel bolt, Isolation transformer is noisy, Provision of 12V and 240V circuit diagrams

**Comment by jphayden** [comment] 2017-09-01 05:18
This is the last remaining electrical issue (I think)
Chris should complete the elec work this pm 1/9
Dee is on site.
I have arrange through Dee for Chris to brief Bill and myself on Monday morning in regard to all the work done

**Comment by DeeTaylor87** [comment] 2017-09-01 12:00
Still has fluctuating unusually loud noise when running the battery charger.  Seems to work fine under heavy load otherwise.  Chris investigating still - it will be important to remind him of the need for investigation on Monday .

**Comment by DeeTaylor87** [comment] 2017-09-03 09:00
Details of device are as follows:
Victron Isolation Tr. 3600W 115/230V
ser # 8719076022527 & HQ1619PWB34
Includes soft start feature to prevent inrush current from blowing shore line.

**Comment by DeeTaylor87** [comment] 2017-09-04 11:51
Booklets of information on the isolation transformer have been left in the manuals folder on board but will need to be scanned. I'm hoping @pjwain  or @paulmc9999  would be kind enough to take that task on (they have been so very generous with their scanning skills in the past....)

**Comment by DeeTaylor87** [comment] 2017-09-04 11:58
Also, the noise in the transformer is still a bit of a mystery. It is related to the battery charger - there is some sort of interference taking place there, but we are unable to identify the cause. The transformer works well under load, but when we are connected to shore power and the battery is charging, there is still an intermittant hum. The only course of action that seems reasonable (without beginning an epic search for an ideal solution) is to turn off the battery charger at night when we are hooked up to mains power. Not the most elegant of solutions, but there is not much to be gained by pursuing this with BME.  I think we might have to be philosophical in this instance.

**Comment by DeeTaylor87** [comment] 2017-09-07 10:01
@jphayden Should this be closed?

**Comment by jphayden** [comment] 2017-09-07 10:02
Yes - completed

**Comment by DeeTaylor87** [comment] 2017-09-07 10:04
Thanks, Jack! 🥇

**Closed by DeeTaylor87** 2017-09-07 10:04 UTC
Labels: BME, Electrics 240V, priority 1: High, Professional Only
