### ISSUE TITLE
Battery monitor unserviceable 

### ISSUE THREAD

**Issue by jphayden** [CanberraOceanRacingClub/namadgi3#217] opened 2017-09-04 22:59 UTC
We had  some strange readings on the battery monitor and on Monday it was not reading amps at all 

 Chris from BM a advised that there was something wrong with the unit . The unit was removed and jphayden took it to Aquavolt for replacement. Aquavolt said it have to be tested in Brisbane and  it is possible but I'm likely will we will get it back by Friday or a new one.
 Note that we do get d voltage reads out on the Bavaria digital display

**Comment by DeeTaylor87** [comment] 2017-09-06 04:12
Picked up the Battery Monitor today. The people in Brisbane (Blue Seas company) say the unit is fine and installation is the problem. The dealer in Roseville said that there are only about 6 wires between the shunt (which really cannot fail - he showed it to me and I agree!)  and the monitor. We need to contact Chris from BME to see if he did in fact test those wires and connections when he tested the unit.

**Comment by DeeTaylor87** [comment] 2017-09-06 04:38
Please refer to issue 41 - which has the complete history of this issue. Not sure how to cross reference on this thing @smr547  Can you help?

**Comment by jphayden** [comment] 2017-09-06 04:57
I have contacted BME and asked them to re install and check ASAP but  before Saturday

**Comment by smr547** [comment] 2017-09-06 06:39
Hi Dee,  To answer your question, you can refer to an issue number by placing a hash symbol immediately before the issue number. This will then create a clickable link. It is good to cross reference both ways. I'll demonstrate below...

I think this is actually a duplicate of #41 but since this item is more current we will close #41

**Comment by DeeTaylor87** [comment] 2017-09-06 06:45
Please note this summary from Chris.  I think he has already done the work.  If it is still faulty, the Aquavolt dealers should be informed. They said they would pay for the freight to send it to Brisbane a second time. They wanted to hear from Chris.
This was the summary I made when I was making notes on what Chris told Bill, Jack and me at the meeting:
Chris tested it and found that it was ok with voltages. He checked all the connections frolm the shunt to the meter and it was all fine. The meter is faulty when it exceeds 10Amps – works ok at 4 to 5 amps it goes haywire. It was discharging when he had the engine running. Jack has taken it to return to the company today (4th September)

**Comment by DeeTaylor87** [comment] 2017-09-07 09:50
Blue Seas monitor is back on board, awaiting electrician tomorrow.

**Comment by DeeTaylor87** [comment] 2017-09-07 11:44
@jphayden @smr547 Investigations this evening have revealed an interesting configuration of wires in the green socket that connects the monitor to the rest of the system. There is a wire which is floating free of the socket. Steven is looking closely at the installation guide to check the rest of the configuration. The issue may be almost solved.  Brilliant work, Steven!

**Comment by smr547** [comment] 2017-09-07 12:52
Thank you for providing the photographs Dee. I don't know about brilliant -- we thought it must be something wrong with the wiring!

Based on the photos and reading the installation manual, there appears to be several issues with the way the BlueSeas 8-pin plug has originally been wired (I'm trying to be polite):

1. Shunt to M2 is clearly NOT a twisted pair -- for correct and reliable operation this *MUST* be replaced with actual twisted pair
1. Shunt to M2 "twisted pair" terminate at the wrong pins (should be 5&6 is 5&7)
1. M2 ``Bat_1 -ve`` line should terminate at pin 7 -- it is absent (I suspect this is this the heavier black line off the LHS of the shunt?)

Given the poor installation quality I think we should also check :

1. Confirm the brown line to pin 4 ``relay VCC`` originates from the Thruster Battery ``-ve`` pole? It will be designated ``Bat 3``
1. Confirm ``Bat 2`` pins 7 & 8 are connected *directly* to the poles of the engine battery
1. Has twisted pair been used for the ``Bat 2`` long run connection -- replace if necessary

Our electrician tomorrow should refer to the [M2 installation manual](http://corc.com.au/Manuals/B46%20Battery%20Monitor%20Installation%20&%20Operations%20Guide.pdf) noting that the unit is an ``1830`` model to operate as a SOC monitor. The wiring diagram at the top left corner of page 5 is what we need to achieve.

**Comment by smr547** [comment] 2017-09-07 13:36
I've further updated my previous advice by amending my comments directly on GitHub. Please use that for reference and *NOT* the resulting email.

The update was necessary to correct errors I made and to cover omission.

This is tedious and time consuming work trying to describe how to correct somebody's poor workmanship.  I've come to the conclusion that the original installation was of such poor quality it should be removed and redone at the original installer's expense. Sadly, I think they may have already been paid.

Again, @bullswool would be interested in these conclusion.

**Comment by smr547** [comment] 2017-09-08 00:02
Chris from BME is at the boat with Dee looking at this issue. Chris has reported his findings to me by phone:

1. All signal cables in the installation are twisted pairs complying with the installation spec -- it's just obvious not in the photographs
1. The chief problem was that the clear wire from one side of the shunt had broken away from pin 6  of the M2 connector -- this would cause confusion to the unit particularly during charging
1. All three  ``+ve``  battery connectors (pins 2, 4 and 8) are effectively sourced from the battery poles 
1. These all have inline 5A fuses as per spec
1. The unit will continue to operate when the boat master switch is turned off -- although the display may turn off after some time it can be reactivated by pressing any button
1. The cable harness is well support by cable ties above the unit allowing enough slack to access and service the unit

Chris and Dee are now testing the unit and will report. Chris is confident the problem has been fixed and the unit is now serviceable.

I'll leave it to Dee to close this issue when testing is complete. I'm pleased the situation was not as dire as I first thought. Flu symptoms, late hour and working from photographs can induce one to take a pessimistic view 🗡   

@jphayden @bullswool will be interested in this outcome

**Comment by jphayden** [comment] 2017-09-08 00:11
Hi Steven,  I think it was only because of your research they we were able to confirm the installation was faulty - gave us  credible information to get BME to look at it more closely 

 Fingers crossed for the final result

**Comment by DeeTaylor87** [comment] 2017-09-08 00:20
The Battery Meter appears to be working fine now. Just a note to let people know that the BM is always on - it is never off, but it does 'sleep' so if it looks off, just press any button and it will come back to show you the state of the battery.  Also, please be aware that if the Voltage is reading below 12V we either need to plug shore power in and turn the main battery charger switch in the cupboard on OR run the engine so that the batteries can charge.   The engine should run at 1000-1200RPM in order to charge it effectively and efficiently. If the battery monitor is reading at 10V or lower, the skipper is starting to damage the battery and MUST pay more attention!

**Comment by jphayden** [comment] 2017-09-08 01:05
Thanks Dee ,  and just to confirm,  is it showing amps  when it is charging and discharging

**Comment by DeeTaylor87** [comment] 2017-09-08 02:05
Yes. It even makes sense to me so it must be good. Little battery graph works. Voltage looks good and amp reading is sensible.

**Comment by jphayden** [comment] 2017-09-08 02:30
Great to hear

**Comment by DaveHolt** [comment] 2017-09-24 01:33
From Bill:
 The battery monitor continues to be a problem. It seems to indicate
normally when the engine is not running.It then goes haywire after start up.
Why is this? Is it incorrectly wired? Has the initial instrument set up been
properly carried out? Could there be some spurious electromagnetic
induction, causing misreading,when charging currents are introduced
following engine startup. The vollage readouts appear to be accurate, it is
the amps and battery capacity readouts that are erratic. I think that the
the majority of the members probably do not understand how voltage relates
to battery state of charge. So,until the problem is rectified, how about we
get a copy of the attached chart(or similar) printed, and placed on board in
the vicinity of the electrical panel. 
![12-v-battery-state-of-charge-website](https://user-images.githubusercontent.com/31207261/30778565-35a3bfde-a11c-11e7-9dc4-d600adb86143.jpg)

**Closed** 2017-12-05 00:13 UTC
