### ISSUE TITLE
Install 12V to 240V inverter

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#180] opened 2017-08-07 09:31 UTC

**Comment by delcosta** [comment] 2017-08-07 09:58
Do we have a quote for this?

**Comment by DeeTaylor87** [comment] 2017-08-07 23:39
Do you have a preferred supplier? Should I ask Quays to quote?

**Comment by jphayden** [comment] 2017-08-08 00:32
We have a quote from the Quays, but Bill (and I) think it is a bit high - I am trying ton get another quote from Marty Anderson or BME

**Comment by DeeTaylor87** [comment] 2017-08-22 11:17
This is a duplicate of issue 44

**Comment by DeeTaylor87** [comment] 2017-08-26 08:41
Inverter has been installed in the storage bay behind the saloon seats.  Still to be tested

**Comment by DeeTaylor87** [comment] 2017-08-31 04:19
Chris electrician from BME thinks it is a good plan to meet with a few of us to go over what has been done, clarify things and confirm best practice in the care of our system

**Comment by DeeTaylor87** [comment] 2017-09-03 09:02
Details of the Inverter are as follows:
Victron Phoenix Inverter Compact 12/2000 230V VE.Bus
Ser # HQ16496J3SF
VE.Bus communication port to allow for remote monitoring and system
interrogation.

**Comment by DeeTaylor87** [comment] 2017-09-04 08:26
When we switch to inverter in the main switch box, the only switches on the main switch board that will  in the cupboard will be the sockets in heads switch and the sockets.  Booklets of information on the inverter have been left in the manuals folder but will need to be scanned. @paulmc9999 @pjwain  Note the warning system for the inverter in the cupboard where the land/inverter switch is.

**Comment by DeeTaylor87** [comment] 2017-09-08 10:09
@bullswool 
At the meeting with Chris, you said you wanted a 'bus' (too technical for me) but I imagine it was to tidy up some wires on the main circuit board which seemed excessive for the space.  Chris decided to install one with a fuse so so now we have an inverter fuse that looks like this ![inverter fuse on board](https://user-images.githubusercontent.com/30706096/30206870-d7fc335e-94d0-11e7-947d-9d672d4840fe.jpg). It has a clear label on it and a little cover over it.  Next to it is the alternator fuse with the same kind of little plastic cover over it.  
![alternator fuse bus](https://user-images.githubusercontent.com/30706096/30206899-eec26824-94d0-11e7-9f59-282188ecbc59.jpg)
Even though they are the same type of cover, we won't be able to get the labels mixed up because the alternator fuse (which is the bus that he needed to install today) had to have a bit cut out of it due to the size of the wire. If you try to put the covers on the wrong fuse bus, the labelled cover to the inverter just wont fit properly on the alternator bus.

**Closed** 2018-02-10 20:02 UTC
Labels: BME, Electrics 12V, Electrics 240V, Professional Only, SOP10, priority 1: High
