### ISSUE TITLE
Check/replace Defibrillator batteries and pads also check for child pads

### ISSUE THREAD

**Issue by DaveHolt** [CanberraOceanRacingClub/namadgi3#289] opened 2018-04-18 23:28 UTC
Check / replace Defibrillator batteries and pads also check for child pads, replace if necessary
St John

**Comment by smr547** [comment] 2021-05-06 00:34
Pads expired 7/2020 -- new pads required
Battery expiry is 10/2023
Chris Green is chasing the pads. Opening this issue until replacement pads have been sourced. @delcosta  and @pjwain will be interested

**Comment by smr547** [comment] 2021-05-06 02:52
Chris Green has sourced supplier in Macquarie Park -- @delcosta Sam, could you pick them up?  Supplier details below. His name is Paul Jones.

[defrib-pads-namadgi.pdf](https://github.com/CanberraOceanRacingClub/namadgi3/files/6431440/defrib-pads-namadgi.pdf)

**Comment by smr547** [comment] 2021-05-22 00:31
New pads installed -- closing this issue

**Comment by smr547** [comment] 2023-01-03 04:04
Recently @PSARN noted:

>Kids Pads expire 31/7/2020
>Adult Pads expire 1/6/2023
>Battery status unknown

Clearly the "unknown" status of the battery is a worry -- reopen this issue as Priority 1

**Comment by smr547** [comment] 2023-01-03 22:31
@mrmrmartin reports that the Battery OK status is confirmed by a light indication on the unit itself.

New pads required before NZ->Fiji trip
Setting priority 2

@peterottesen will be interested

**Comment by smr547** [comment] 2024-03-20 06:00
Linda from the Debrib company will send a quote for new pads and battery. We definitely need to replace the pads -- the battery seems to be OK

**Comment by smr547** [comment] 2024-03-21 21:46
Quote from AEDS
```
Hi Steven
Thanks for your call this afternoon. Please find prices below. All items are in stock
HeartStart HS1 First Aid Defibrillator
M5071A – Adult SMART Pads - $134.00 GST Free
M5072A- Child SMART Pads – $236.00 GST Free
HeartStart Battery - $255.00 GST Free
Freight will be $20.00 plus GST
If you wish to proceed with the purchase please confirm your order by replying to my e mail and providing a delivery address. I will then forward an invoice to you which can be paid by EFT or credit card.
Kind regards,
Linda Morris
Australian Defibrillators
Ph: 1 300 DEFIBS (1 300 333 427)
[www.aeds.com.au](http://www.aeds.com.au/)
```

Asked the committee 

```
Dear Committee,

The Defibrillator pads have expired -- it's $370 total for an adult and a child set. 

The battery is in date but should be replaced Nov 2025

Is the committee happy to go ahead?

regards
Steven
```

**Comment by smr547** [comment] 2024-04-29 22:05
New pads (adult) and fresh battery installed. Child pads stored in box with the defibrillator.  Unit tested Ok. Closing this issues. @mgrybaitis will be interested.

**Closed by smr547** 2024-04-29 22:05 UTC
Labels: Priority_2, shopping list, Routine Maintenance, WorkingBee
