### ISSUE TITLE
Engine & Saildrive - 250hr Service due 3900 hrs

### ISSUE THREAD

**Issue by pcbaston** [CanberraOceanRacingClub/namadgi3#696] opened 2023-04-05 12:31 UTC
Previous service performed at Opua, NZ by Seapower April 2023 at 3276hrs.

New issue for next service interval.  500hr service due @ 3775hrs.

**Comment by smr547** [comment] 2023-09-28 03:56
@delcosta  reports:

Service done at Port Moselle 

> early August at engine hours 3651 hrs. Updating the title of this issue -- service now due 3900hrs

Thanks for the report Sam.

**Comment by pcbaston** [comment] 2023-09-28 21:40
Concur.
Sam had the engine serviced as I had advised him during his cruise in Fiji.
There is no method, other than someone remembering, to trigger an
engine/saildrive service.

I propose we add this important information to the Skipper's handover
notes, so that incoming skippers are advised how many engine hours are
remaining until a service is due (every 250 hours as agreed by CORC
committee previously). This would negate the need for a GITHUB Issue and
put the onus on the Skippers.  ie: if there are less than 50 hours
remaining, someone SHOULD be asking when the engine service is booked for.

My thoughts...

*Paul Baston*

**Comment by smr547** [comment] 2023-09-28 22:53
It's a good idea that we put the onus back onto the current skipper to  organise an engine service

@peterottesen @delcosta @DimitD

**Comment by pcbaston** [comment] 2023-09-29 06:14
I did not mean to put the onus to arrange the service, but to be aware that
a service is due and to speak to someone (Maintenance Manager most likely)
to arrange with a recognised supplier to have the service done - obviously
in concert with the skipper at the time - who may have to return to port a
day ahead of schedule to have the service done. Unfortunately, it would be
difficult to predict when a day could be made available for such
maintenance when the vessel is being used through the booking system
(especially when out of SYdney area).

Regards,

*Paul Baston*

**Comment by smr547** [comment] 2023-10-04 01:15
Noted that this is a duplicate of #214 -- closing this issue and updating title of #214

**Closed by smr547** 2023-10-04 01:15 UTC
Labels: Engine, Priority_1, Routine Maintenance, Boatworks
