### ISSUE TITLE
Find mooring or berth urgently

### ISSUE THREAD

**Issue by smr547** [CanberraOceanRacingClub/namadgi3#215] opened 2017-08-29 03:14 UTC
Quays have advised that Namadgi 3 must go on a mooring today or tomorrow and then leave Quays completely by 0800 Monday 4/9/2017 -- Quays are currently booked solid and have no space for us.

@jphayden is asking @DeeTaylor87 if she would kindly do one of her "ring-arounds" to see if she can find us a spot while preparations for B/Bay are finalised.

Please use this item for all communication on this matter.

@delcosta @mrmrmartin @peterottesen @jphayden @SimonRD and @pjwain will be interested in this issue.

**Comment by peterottesen** [comment] 2017-08-29 03:24
Sorry, but cannot access Gitup at the moment. 

I have spoken to sailmaker (hoods) and rigger (mario) about the 3rd reef. Hood can do but will take a week. We have to deliver the sail, with battens removed  Mario will check the boat before Friday and advise on a solution for the boom and deck hardware. I told him the boat goes on a mooring this Friday. He thinks there should not be a problem and knows we want this done by 8 September.  He recommends we use the boom topping lift and fit a Cunningham tackle from the base of the mast to the tack.

I asked him about jack stays. He says the Whitworth product we have identified is the best solution and he can provide at the same cost. He says it has good features. He will also confirm that it is cat 1 compliant. 



-------- Original Message ----------

 

	Quays have advised that Namadgi 3 must go on a mooring today or
tomorrow and then leave Quays completely by 0800 Monday 4/9/2017 --
Quays are currently booked solid and have no space for us. 

	@jphayden [1] is asking @DeeTaylor87 [2] if she would kindly do one
of her "ring-arounds" to see if she can find us a spot while
preparations for B/Bay are finalised. 

	Please use this item for all communication on this matter. 

	@delcosta [3] @mrmrmartin [4] @peterottesen [5] @jphayden [6]
@SimonRD [7] and @pjwain [8] will be interested in this issue. 

	--
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [9], or mute the
thread [10].   
	*   

Links:
------
[1] https://githubcom/jphayden
[2] https://github.com/deetaylor87
[3] https://github.com/delcosta
[4] https://github.com/mrmrmartin
[5] https://github.com/peterottesen
[6] https://github.com/jphayden
[7] https://github.com/simonrd
[8] https://github.com/pjwain
[9] https://github.com/CanberraOceanRacingClub/namadgi3/issues/215
[10]

**Comment by DeeTaylor87** [comment] 2017-08-29 03:29
Will start searching now and let you know

**Comment by DeeTaylor87** [comment] 2017-08-29 04:18
Just a preliminary report to let you know what is happening.
Sirsi - no vacancy
RPAYC - still waiting on a call to be returned
Called a couple of other small marinas who have a history of not returning calls and still no returned calls
Holmeport - Lady is fairly confident there is a berth available but cannot confirm 100% until Friday. Casual rate cost of berth for a week is $740
Will still try for a back-up plan and let you know when I hear back from RPAYC
@smr547 @jphayden @peterottesen @delcosta @mrmrmartin @SRDunlop @pjwain @DaveHolt

**Comment by mrmrmartin** [comment] 2017-08-30 01:18
Hi Dee

Just thinking laterally - perhaps Simon Dunlop can contact PAYC since he is a member and might have more sway

________________________________

**Comment by DeeTaylor87** [comment] 2017-08-30 01:49
Yes - that might be good. RPAYC have confirmed that there is a berth available. I have just asked her if she would prefer to deal directly with Simon, or she is happy to continue discussion with me (his representative)

**Comment by smr547** [comment] 2017-08-30 01:51
Excellent -- deal direct if you can as Simon is away (I think)

**Comment by DeeTaylor87** [comment] 2017-08-30 01:53
The price is $61 per night at RPAYC.  Should we confirm booking?

**Comment by DeeTaylor87** [comment] 2017-08-30 01:53
I might just text Simon and let him know....

**Comment by jphayden** [comment] 2017-08-30 03:24
Great Dee
How long can we have it for

Regards.  Jack

**Comment by DeeTaylor87** [comment] 2017-08-30 10:52
Hi Jack - sorry it has taken a while to get back to you.  We have an agreed period till the 10th, but should be able to negotiate a few days after that if needed. If we need to extend the booking for another week or so, we will have to do so soon because she will be taking bookings for the berth as they come in.  I imagine we should be able to get away by the 10th Sept?

**Comment by jphayden** [comment] 2017-08-30 12:02
Good work Dee - hopefully, that will be sufficient.
Some more detail tomorrow.

**Comment by DeeTaylor87** [comment] 2017-08-31 01:44
Cheers. This one clsed

**Closed by DeeTaylor87** 2017-08-31 01:44 UTC
Labels: priority 1: High
